"""Shared converter primitives for Fleetlytics JSON-to-SQL scaffolding."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, ClassVar

from src.config import get_db_schema

from .sql_writer import write_sql_file


class SQLExpression:
    """Wrapper for raw SQL fragments that should not be quoted."""

    __slots__ = ("sql",)

    def __init__(self, sql: str) -> None:
        self.sql = sql


def _quote_identifier(identifier: str) -> str:
    """Quote a SQL identifier safely for generated SQL."""

    return '"' + identifier.replace('"', '""') + '"'


def _render_literal(value: Any) -> str:
    """Render a Python value as a SQL literal."""

    if value is None:
        return "NULL"
    if isinstance(value, SQLExpression):
        return value.sql
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, datetime):
        iso_value = value.astimezone(timezone.utc).isoformat()
        return "'" + iso_value.replace("'", "''") + "'::timestamptz"
    if isinstance(value, (dict, list)):
        import json

        json_value = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        return "'" + json_value.replace("'", "''") + "'::jsonb"
    if isinstance(value, Path):
        value = str(value)
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return "'" + str(value).replace("'", "''") + "'"


def build_upsert_sql(
    *,
    schema: str,
    table: str,
    rows: Sequence[Mapping[str, Any]],
    conflict_columns: Sequence[str],
    updatable_columns: Sequence[str],
    generated_columns: set[str],
    source_filename: str,
    run_dir: Path,
) -> str:
    """Build a transaction-wrapped UPSERT SQL document."""

    if not rows:
        raise ValueError("At least one row is required to generate SQL.")

    ordered_columns: list[str] = []
    for row in rows:
        for column in row.keys():
            if column in generated_columns or column in ordered_columns:
                continue
            ordered_columns.append(column)

    update_columns = [
        column
        for column in updatable_columns
        if column not in generated_columns
        and column not in conflict_columns
        and column not in {"last_synced_at", "updated_at"}
    ]
    audit_columns = [column for column in ("last_synced_at", "updated_at") if column in ordered_columns]

    insert_columns_sql = ", ".join(_quote_identifier(column) for column in ordered_columns)
    values_sql_rows: list[str] = []
    for row in rows:
        rendered_values = [_render_literal(row.get(column)) for column in ordered_columns]
        values_sql_rows.append("(" + ", ".join(rendered_values) + ")")

    conflict_sql = ", ".join(_quote_identifier(column) for column in conflict_columns)
    update_assignments = [
        _quote_identifier(column) + " = EXCLUDED." + _quote_identifier(column)
        for column in update_columns
    ]
    update_assignments.extend(_quote_identifier(column) + " = now()" for column in audit_columns)

    if update_assignments:
        comparison_columns = [column for column in update_columns if column not in audit_columns]
        where_clause = " OR ".join(
            _quote_identifier(table)
            + "."
            + _quote_identifier(column)
            + " IS DISTINCT FROM EXCLUDED."
            + _quote_identifier(column)
            for column in comparison_columns
        )
        conflict_clause = (
            "ON CONFLICT (" + conflict_sql + ") DO UPDATE SET "
            + ", ".join(update_assignments)
            + (f" WHERE {where_clause}" if where_clause else "")
        )
    else:
        conflict_clause = "ON CONFLICT (" + conflict_sql + ") DO NOTHING"

    header_lines = [
        "-- Generated by Fleetlytics converters",
        f"-- Source: {source_filename}",
        f"-- Run: {run_dir}",
        f"-- Table: {table}",
        f"-- Rows: {len(rows)}",
        f"-- Generated at: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "",
    ]

    sql_lines = [
        "BEGIN;",
        f"INSERT INTO {_quote_identifier(schema)}.{_quote_identifier(table)} ({insert_columns_sql})",
        "VALUES",
        ",\n".join("    " + row_sql for row_sql in values_sql_rows),
        conflict_clause,
        "RETURNING (xmax = 0) AS inserted;",
        "COMMIT;",
    ]

    return "\n".join(header_lines + sql_lines) + "\n"


class BaseConverter(ABC):
    """Abstract base class for per-entity JSON-to-SQL converters."""

    entity_name: ClassVar[str]
    source_filename: ClassVar[str]
    target_table: ClassVar[str]
    conflict_columns: ClassVar[list[str]]
    updatable_columns: ClassVar[list[str]]
    generated_columns: ClassVar[set[str]]
    sql_filename: ClassVar[str] = ""

    @abstractmethod
    def load_source(self, run_dir: Path) -> list[dict[str, Any]] | dict[str, Any]:
        """Load the source JSON payload for the converter."""

    @abstractmethod
    def map_record(self, record: Mapping[str, Any]) -> dict[str, Any]:
        """Map one API record to a database row dict."""

    def convert(self, records: list[dict[str, Any]] | dict[str, Any]) -> list[dict[str, Any]]:
        """Convert loaded records into database row dictionaries."""

        if isinstance(records, dict):
            if "items" in records and isinstance(records["items"], list):
                source_records: Sequence[Mapping[str, Any]] = records["items"]
            elif "data" in records and isinstance(records["data"], list):
                source_records = records["data"]
            else:
                source_records = [records]
        else:
            source_records = records

        return [self.map_record(record) for record in source_records]

    def write_sql(self, rows: Sequence[Mapping[str, Any]], sql_dir: Path) -> Path:
        """Write the converter output to a SQL file."""

        if not rows:
            raise ValueError(f"{self.entity_name} produced no rows to write.")

        schema = get_db_schema()
        run_dir = Path(sql_dir).parent
        output_name = self.sql_filename or f"{self.entity_name}.sql"
        sql_text = build_upsert_sql(
            schema=schema,
            table=self.target_table,
            rows=rows,
            conflict_columns=self.conflict_columns,
            updatable_columns=self.updatable_columns,
            generated_columns=self.generated_columns,
            source_filename=self.source_filename,
            run_dir=run_dir,
        )
        return write_sql_file(Path(sql_dir) / output_name, sql_text)
