"""Trip-location JSON-to-SQL converter."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

from Fleetlytics.converters.base import SQLExpression, build_upsert_sql
from Fleetlytics.converters.coercers import to_float, to_int
from Fleetlytics.converters.paths import sql_dir_for_run
from Fleetlytics.converters.sql_writer import write_sql_file

from src.config import get_db_schema

LOGGER = logging.getLogger(__name__)


def _json_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def map_trip_location(row: Mapping[str, Any]) -> dict[str, Any] | None:
    """Map one API trip-location row to a database row."""

    trip_id = _json_text(row.get("tripId"))
    account_id = to_int(row.get("accountId"))
    timestamp_ms = to_int(row.get("timestamp"))
    latitude = to_float(row.get("latitude"))
    longitude = to_float(row.get("longitude"))
    if trip_id is None or account_id is None or timestamp_ms is None or latitude is None or longitude is None:
        return None

    return {
        "trip_id": trip_id,
        "account_id": account_id,
        "timestamp_ms": timestamp_ms,
        "latitude": latitude,
        "longitude": longitude,
        "last_synced_at": SQLExpression("now()"),
    }


class TripLocationConverter:
    """Convert trip-location JSON payloads into an UPSERT SQL file."""

    entity_name = "trip_locations"
    source_filename = "trip_locations.json"
    target_table = "sirqul_trip_locations"
    conflict_columns = ["trip_id", "account_id", "timestamp_ms", "latitude", "longitude"]
    updatable_columns = ["last_synced_at"]
    generated_columns = {"id", "created_at", "updated_at", "timestamp_datetime"}
    sql_filename = "005_trip_locations.sql"

    def load_source(self, run_dir: Path) -> list[dict[str, Any]]:
        """Load the flat trip-location JSON payload."""

        source_path = Path(run_dir) / self.source_filename
        if not source_path.exists():
            raise FileNotFoundError(f"Missing trip location source file: {source_path}")

        raw_text = source_path.read_text(encoding="utf-8").strip()
        if not raw_text:
            raise ValueError(f"Trip location source file is empty: {source_path}")

        try:
            payload = json.loads(raw_text)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Trip location source file is not valid JSON: {source_path}") from exc

        if not isinstance(payload, list):
            raise ValueError(f"Trip location source must be a JSON list: {source_path}")

        rows: list[dict[str, Any]] = []
        for row in payload:
            if not isinstance(row, dict):
                raise ValueError(f"Trip location rows must be JSON objects: {source_path}")
            rows.append(row)
        return rows

    @staticmethod
    def _noop_sql(source_filename: str, run_dir: Path, table_name: str) -> str:
        header_lines = [
            "-- Generated by Fleetlytics converters",
            f"-- Source: {source_filename}",
            f"-- Run: {run_dir}",
            f"-- Table: {table_name}",
            "-- Rows: 0",
            f"-- Generated at: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
            "",
        ]
        return "\n".join(header_lines + ["BEGIN;", "COMMIT;"]) + "\n"

    def write_run_sql(self, run_dir: Path) -> Path:
        """Convert the latest trip-location payload and write the SQL output."""

        records = self.load_source(run_dir)
        mapped_rows: list[dict[str, Any]] = []
        skipped_rows = 0
        for index, record in enumerate(records, start=1):
            mapped_row = map_trip_location(record)
            if mapped_row is None:
                skipped_rows += 1
                LOGGER.warning(
                    "trip_location_index=%s reason=%s row=%r",
                    index,
                    "missing_required_fields",
                    record,
                )
                continue
            mapped_rows.append(mapped_row)

        deduped_rows: list[dict[str, Any]] = []
        seen_keys: set[tuple[Any, ...]] = set()
        duplicate_count = 0
        for row in mapped_rows:
            key = (
                row.get("trip_id"),
                row.get("account_id"),
                row.get("timestamp_ms"),
                row.get("latitude"),
                row.get("longitude"),
            )
            if key in seen_keys:
                duplicate_count += 1
                continue
            seen_keys.add(key)
            deduped_rows.append(row)

        if duplicate_count:
            LOGGER.warning("trip_location_duplicate_rows_suppressed=%s", duplicate_count)

        LOGGER.info(
            "trip_locations_total=%s trip_locations_resolved=%s trip_locations_skipped=%s trip_locations_deduped=%s",
            len(records),
            len(deduped_rows),
            skipped_rows,
            duplicate_count,
        )

        sql_dir = sql_dir_for_run(run_dir)
        if not deduped_rows:
            output_path = write_sql_file(
                sql_dir / self.sql_filename,
                self._noop_sql(self.source_filename, run_dir, self.target_table),
            )
            LOGGER.warning("No resolvable trip locations were found; wrote no-op SQL.")
            return output_path

        output_path = write_sql_file(
            sql_dir / self.sql_filename,
            build_upsert_sql(
                schema=get_db_schema(),
                table=self.target_table,
                rows=deduped_rows,
                conflict_columns=self.conflict_columns,
                updatable_columns=self.updatable_columns,
                generated_columns=self.generated_columns,
                source_filename=self.source_filename,
                run_dir=Path(run_dir),
            ),
        )
        return output_path


def convert_trip_locations(run_dir: Path) -> Path:
    """Convert the latest trip-location payload into ``005_trip_locations.sql``."""

    converter = TripLocationConverter()
    return converter.write_run_sql(run_dir)
